import 'dart:io';

// `hide isNull`: drift exports a SQL `isNull` expression builder, and this
// file asserts with the matcher of the same name.
import 'package:drift/drift.dart' hide isNull;
import 'package:factorino/core/security/database_encryption_key.dart';
import 'package:factorino/data/database/app_database.dart';
import 'package:factorino/data/database/database_bootstrap.dart';
import 'package:factorino/data/database/encrypted_database.dart';
import 'package:factorino/data/models/app_settings.dart';
import 'package:factorino/data/models/invoice_status.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

// The old schemas, as generated by `drift_dev schema generate` for the unit
// migration tests. Imported across directories rather than duplicated: a
// hand-written copy of an old schema is a copy that can drift from the dump the
// real migration is diffed against, and then this proof would be checking a
// version that never existed.
import '../test/data/database/generated/schema_v1.dart' as v1;
import '../test/data/database/generated/schema_v2.dart' as v2;

/// The v2 -> v3 migration (D-052), on the real target.
///
/// The unit suite proves the same properties on the Dart VM. This runs on the
/// device for the reason the D-020 and D-048 proofs do: the open question is
/// whether the **native** SQLite found through Flutter's own packaging path
/// behaves the same way. `ALTER TABLE ... ADD COLUMN` on a table that already
/// holds rows, and a `NOT NULL DEFAULT` column added to a table with an
/// existing row, are both things the native library decides — and "same table,
/// same result as last time" is the assumption that makes a proof pointless.
///
/// **Two ladders, because they are different code paths.** A device updating
/// from the last release arrives at v2 and runs one step. A device that has
/// never been updated arrives at v1 and runs two, the first of which rebuilds
/// `invoices` from the table as it is declared today — so the second finds the
/// new columns already there. That difference is invisible in the source and
/// is where the migration would fail for exactly the users furthest behind.
///
/// Uses probe filenames, so running it never touches the real application
/// database.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  final int now = DateTime.utc(2026, 8, 24, 12).millisecondsSinceEpoch;

  Future<File> freshProbe(String name) async {
    final File file = await defaultDatabaseFile(name: name);
    for (final String suffix in <String>['', '-wal', '-shm']) {
      final File stale = File('${file.path}$suffix');
      if (stale.existsSync()) stale.deleteSync();
    }
    return file;
  }

  Future<int> pragmaInt(GeneratedDatabase db, String pragma) async {
    final QueryRow row = await db.customSelect('pragma $pragma').getSingle();
    return row.data.values.first as int;
  }

  Future<int> count(GeneratedDatabase db, String table) async {
    final QueryRow row = await db
        .customSelect('select count(*) as c from $table')
        .getSingle();
    return row.read<int>('c');
  }

  /// Everything both ladders assert about the migrated file.
  Future<void> expectMigrated(
    AppDatabase migrated,
    File file, {
    required String label,
    required int versionBefore,
    required int items,
    required int payments,
  }) async {
    final int version = await pragmaInt(migrated, 'user_version');
    final int fk = await pragmaInt(migrated, 'foreign_keys');

    // soft-delete-exempt: a migration assertion over every row.
    final InvoiceRow invoice = await migrated
        .select(migrated.invoices)
        .getSingle();
    // soft-delete-exempt: the single settings row, asserted after migration.
    final SettingsRow settings = await migrated
        .select(migrated.settings)
        .getSingle();

    debugPrint(
      '=== D-052 MIGRATION PROOF ($label) on '
      '${Platform.operatingSystem} ===',
    );
    debugPrint('database file : ${file.path}');
    debugPrint('user_version  : $versionBefore -> $version');
    debugPrint('foreign_keys  : $fk');
    debugPrint('invoices      : ${await count(migrated, "invoices")}');
    debugPrint('invoice_items : ${await count(migrated, "invoice_items")}');
    debugPrint('payments      : ${await count(migrated, "payments")}');
    debugPrint('payment term  : ${settings.paymentTermDays}');
    debugPrint('snapshot      : ${invoice.customerNameSnapshot ?? "<null>"}');
    debugPrint('file state    : ${inspectDatabaseFile(file).name}');

    // **`migrated.schemaVersion`, not a literal**, as
    // `invoice_number_migration_proof_test.dart` already had it. This one read
    // the version it was written for and kept reading it through every later
    // step, because an on-device proof is not in `flutter test` and nobody
    // re-ran it — so the assertion that says "the ladder finished" was pinned
    // to a version the application had long left behind.
    expect(version, migrated.schemaVersion);
    expect(fk, 1, reason: 'the migration must leave foreign keys on');

    // The children. `ADD COLUMN` drops nothing, so there is nothing to
    // cascade — but the v1 ladder runs a table rebuild first, and this is the
    // count that would read zero if the device's SQLite handled the
    // foreign-key pragma differently from the VM's.
    expect(await count(migrated, 'invoice_items'), items);
    expect(await count(migrated, 'payments'), payments);

    expect(invoice.number, 'INV-1405-0001');
    expect(invoice.numberSequence, 1);
    expect(invoice.grandTotalRial, 21230000);

    // An invoice issued before v3 gets no snapshot, and gets none invented for
    // it: there is no honest value to backfill, and the read path falls back to
    // the live customer (D-052).
    expect(invoice.customerNameSnapshot, isNull);
    expect(invoice.customerNationalIdSnapshot, isNull);

    // The `NOT NULL DEFAULT` column, on a settings row that predates it.
    expect(settings.paymentTermDays, kDefaultPaymentTermDays);

    // Still encrypted afterwards.
    expect(inspectDatabaseFile(file), DatabaseFileState.encrypted);

    // And the columns are writable, not merely present: the snapshot `issue()`
    // takes has to land on this device, not only on the VM.
    await (migrated.update(
      migrated.invoices,
    )..where((r) => r.id.equals(invoice.id))).write(
      const InvoicesCompanion(
        customerNameSnapshot: Value<String?>('مشتری نمونه'),
        customerNationalIdSnapshot: Value<String?>('0079542311'),
      ),
    );
    // soft-delete-exempt: a migration assertion over every row.
    final InvoiceRow written = await migrated
        .select(migrated.invoices)
        .getSingle();
    expect(written.customerNameSnapshot, 'مشتری نمونه');
    expect(written.customerNationalIdSnapshot, '0079542311');
  }

  testWidgets('a v2 database upgrades to v3 without losing data', (_) async {
    final File file = await freshProbe('snapshot_probe_v2.db');
    final DatabaseEncryptionKey key =
        await const SecureStorageDatabaseKeyStore().obtain();

    final v2.DatabaseAtV2 old = v2.DatabaseAtV2(
      openEncryptedDatabase(file: file, key: key),
    );
    await old.batch((Batch batch) {
      batch.insert(
        old.settings,
        v2.SettingsCompanion.insert(id: 's', createdAt: now, updatedAt: now),
      );
      batch.insert(
        old.customers,
        v2.CustomersCompanion.insert(
          id: 'c1',
          createdAt: now,
          updatedAt: now,
          fullName: 'مشتری نمونه',
        ),
      );
      batch.insert(
        old.invoices,
        v2.InvoicesCompanion.insert(
          id: 'i1',
          createdAt: now,
          updatedAt: now,
          number: const Value<String>('INV-1405-0001'),
          numberYear: const Value<int>(1405),
          numberSequence: const Value<int>(1),
          customerId: 'c1',
          issueDate: now,
          status: InvoiceStatus.partiallyPaid.index,
          grandTotalRial: const Value<int>(21230000),
        ),
      );
      batch.insertAll(old.invoiceItems, <v2.InvoiceItemsCompanion>[
        for (int i = 0; i < 2; i++)
          v2.InvoiceItemsCompanion.insert(
            id: 'item-$i',
            createdAt: now,
            updatedAt: now,
            invoiceId: 'i1',
            titleSnapshot: 'خدمات',
            unitSnapshot: 'عدد',
            unitPriceRial: 1000000,
            quantityMilli: 1000,
            resolvedTaxRateBp: 1000,
          ),
      ]);
      batch.insert(
        old.payments,
        v2.PaymentsCompanion.insert(
          id: 'p1',
          createdAt: now,
          updatedAt: now,
          invoiceId: 'i1',
          amountRial: 6000000,
          paidAt: now,
          method: 0,
        ),
      );
    });

    final int versionBefore = await pragmaInt(old, 'user_version');
    expect(versionBefore, 2, reason: 'the probe must start life as a v2 file');
    await old.close();

    final AppDatabase migrated = await openAppDatabase(file: file);
    try {
      await expectMigrated(
        migrated,
        file,
        label: 'v2 -> v3',
        versionBefore: versionBefore,
        items: 2,
        payments: 1,
      );
    } finally {
      await migrated.close();
      for (final String suffix in <String>['', '-wal', '-shm']) {
        final File probe = File('${file.path}$suffix');
        if (probe.existsSync()) probe.deleteSync();
      }
    }
  });

  testWidgets('a v1 database reaches v3 through both steps', (_) async {
    // The device that has not been updated since the first release. Its first
    // step rebuilds `invoices` at the current declaration, so the second finds
    // the snapshot columns already present — the path where a plain
    // `addColumn` fails with `duplicate column name`, on open, leaving the
    // database unopenable for exactly those users.
    final File file = await freshProbe('snapshot_probe_v1.db');
    final DatabaseEncryptionKey key =
        await const SecureStorageDatabaseKeyStore().obtain();

    final v1.DatabaseAtV1 old = v1.DatabaseAtV1(
      openEncryptedDatabase(file: file, key: key),
    );
    await old.batch((Batch batch) {
      batch.insert(
        old.settings,
        v1.SettingsCompanion.insert(id: 's', createdAt: now, updatedAt: now),
      );
      batch.insert(
        old.customers,
        v1.CustomersCompanion.insert(
          id: 'c1',
          createdAt: now,
          updatedAt: now,
          fullName: 'مشتری نمونه',
        ),
      );
      batch.insert(
        old.invoices,
        v1.InvoicesCompanion.insert(
          id: 'i1',
          createdAt: now,
          updatedAt: now,
          number: 'INV-1405-0001',
          numberYear: 1405,
          numberSequence: 1,
          customerId: 'c1',
          issueDate: now,
          status: InvoiceStatus.partiallyPaid.index,
          grandTotalRial: const Value<int>(21230000),
        ),
      );
      batch.insertAll(old.invoiceItems, <v1.InvoiceItemsCompanion>[
        for (int i = 0; i < 2; i++)
          v1.InvoiceItemsCompanion.insert(
            id: 'item-$i',
            createdAt: now,
            updatedAt: now,
            invoiceId: 'i1',
            titleSnapshot: 'خدمات',
            unitSnapshot: 'عدد',
            unitPriceRial: 1000000,
            quantityMilli: 1000,
            resolvedTaxRateBp: 1000,
          ),
      ]);
      batch.insert(
        old.payments,
        v1.PaymentsCompanion.insert(
          id: 'p1',
          createdAt: now,
          updatedAt: now,
          invoiceId: 'i1',
          amountRial: 6000000,
          paidAt: now,
          method: 0,
        ),
      );
    });

    final int versionBefore = await pragmaInt(old, 'user_version');
    expect(versionBefore, 1, reason: 'the probe must start life as a v1 file');
    await old.close();

    final AppDatabase migrated = await openAppDatabase(file: file);
    try {
      await expectMigrated(
        migrated,
        file,
        label: 'v1 -> v3',
        versionBefore: versionBefore,
        items: 2,
        payments: 1,
      );
    } finally {
      await migrated.close();
      for (final String suffix in <String>['', '-wal', '-shm']) {
        final File probe = File('${file.path}$suffix');
        if (probe.existsSync()) probe.deleteSync();
      }
    }
  });
}
