import 'dart:io';

import 'package:drift/drift.dart';
import 'package:factorino/core/security/database_encryption_key.dart';
import 'package:factorino/data/database/app_database.dart';
import 'package:factorino/data/database/database_bootstrap.dart';
import 'package:factorino/data/database/encrypted_database.dart';
import 'package:factorino/data/models/invoice_status.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

// The v1 schema, as generated by `drift_dev schema generate` for the unit
// migration test. Imported across directories rather than duplicated: a
// hand-written copy of the old schema is a copy that can drift from the dump
// the real migration is diffed against, and then this proof would be checking
// a v1 that never existed.
import '../test/data/database/generated/schema_v1.dart' as v1;

/// The v1 -> v2 migration (D-048), on the real target.
///
/// The unit test in `test/data/database/` proves the same property on the Dart
/// VM. This one exists for the same reason the D-020 encryption proof does: the
/// open question on a device is whether the **native** library found through
/// Flutter's own packaging path behaves the same way. This migration is a
/// 12-step table rebuild that turns foreign keys off and on around a `DROP
/// TABLE`, and `PRAGMA foreign_keys` is a connection-level setting handled by
/// that native library. A migration that passes on the VM and cascades on
/// device would take every invoice line and payment the user has, and the only
/// place to find that out is the device.
///
/// It is an integration test rather than a manual check for the reason D-020
/// gives: it runs on the real target, it is repeatable, and it cannot silently
/// rot.
///
/// Uses a probe filename, so running it never touches the real application
/// database.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('a v1 database with invoices upgrades without losing data', (
    _,
  ) async {
    final file = await defaultDatabaseFile(name: 'migration_probe.db');
    for (final suffix in <String>['', '-wal', '-shm']) {
      final stale = File('${file.path}$suffix');
      if (stale.existsSync()) stale.deleteSync();
    }

    final int now = DateTime.utc(2026, 8, 24, 12).millisecondsSinceEpoch;

    // ---- build a v1 database, through the real encrypted opener ------------
    final key = await const SecureStorageDatabaseKeyStore().obtain();
    final v1.DatabaseAtV1 old = v1.DatabaseAtV1(
      openEncryptedDatabase(file: file, key: key),
    );

    await old.batch((Batch batch) {
      batch.insert(
        old.settings,
        v1.SettingsCompanion.insert(id: 's', createdAt: now, updatedAt: now),
      );
      batch.insert(
        old.customers,
        v1.CustomersCompanion.insert(
          id: 'c1',
          createdAt: now,
          updatedAt: now,
          fullName: 'مشتری نمونه',
        ),
      );
      batch.insert(
        old.invoices,
        v1.InvoicesCompanion.insert(
          id: 'i1',
          createdAt: now,
          updatedAt: now,
          number: 'INV-1405-0001',
          numberYear: 1405,
          numberSequence: 1,
          customerId: 'c1',
          issueDate: now,
          status: InvoiceStatus.partiallyPaid.index,
          grandTotalRial: const Value<int>(21230000),
        ),
      );
      batch.insertAll(old.invoiceItems, <v1.InvoiceItemsCompanion>[
        for (int i = 0; i < 2; i++)
          v1.InvoiceItemsCompanion.insert(
            id: 'item-$i',
            createdAt: now,
            updatedAt: now,
            invoiceId: 'i1',
            titleSnapshot: 'خدمات',
            unitSnapshot: 'عدد',
            unitPriceRial: 1000000,
            quantityMilli: 1000,
            resolvedTaxRateBp: 1000,
          ),
      ]);
      batch.insert(
        old.payments,
        v1.PaymentsCompanion.insert(
          id: 'p1',
          createdAt: now,
          updatedAt: now,
          invoiceId: 'i1',
          amountRial: 6000000,
          paidAt: now,
          method: 0,
        ),
      );
    });

    final int versionBefore =
        (await old.customSelect('pragma user_version').getSingle())
                .data
                .values
                .first
            as int;
    expect(versionBefore, 1, reason: 'the probe must start life as a v1 file');
    await old.close();

    // ---- reopen through the production bootstrap: the migration runs -------
    final AppDatabase migrated = await openAppDatabase(file: file);

    try {
      Future<int> count(String table) async {
        final row = await migrated
            .customSelect('select count(*) as c from $table')
            .getSingle();
        return row.read<int>('c');
      }

      final int version =
          (await migrated.customSelect('pragma user_version').getSingle())
                  .data
                  .values
                  .first
              as int;
      final int fk =
          (await migrated.customSelect('pragma foreign_keys').getSingle())
                  .data
                  .values
                  .first
              as int;

      debugPrint(
        '=== D-048 MIGRATION PROOF on ${Platform.operatingSystem} ===',
      );
      debugPrint('database file : ${file.path}');
      debugPrint('user_version  : $versionBefore -> $version');
      debugPrint('foreign_keys  : $fk');
      debugPrint('invoices      : ${await count("invoices")}');
      debugPrint('invoice_items : ${await count("invoice_items")}');
      debugPrint('payments      : ${await count("payments")}');
      debugPrint('file state    : ${inspectDatabaseFile(file).name}');

      // The whole ladder runs on open, so a v1 file lands on the newest
      // schema rather than stopping at this migration's own version.
      expect(version, migrated.schemaVersion);
      expect(fk, 1, reason: 'alterTable must restore foreign keys');

      expect(await count('invoices'), 1);
      // The cascade check, and the whole reason this runs on a device: step 6
      // of the rebuild is `DROP TABLE invoices`, which with foreign keys on
      // deletes every line and payment through ON DELETE CASCADE.
      expect(await count('invoice_items'), 2);
      expect(await count('payments'), 1);
      expect(await count('customers'), 1);

      // soft-delete-exempt: a migration assertion over every row.
      final InvoiceRow invoice = await migrated
          .select(migrated.invoices)
          .getSingle();
      expect(invoice.number, 'INV-1405-0001');
      expect(invoice.numberYear, 1405);
      expect(invoice.numberSequence, 1);
      expect(invoice.grandTotalRial, 21230000);

      // Still encrypted after a table rebuild that rewrote the whole file.
      expect(inspectDatabaseFile(file), DatabaseFileState.encrypted);

      // The mechanism D-048 turns on: NULLs are distinct in a unique index, so
      // two numberless drafts coexist where an empty-string sentinel could not.
      for (int i = 0; i < 2; i++) {
        await migrated
            .into(migrated.invoices)
            .insert(
              InvoicesCompanion.insert(
                customerId: 'c1',
                issueDate: now,
                status: InvoiceStatus.draft,
              ),
            );
      }
      expect(await count('invoices'), 3);
    } finally {
      await migrated.close();
      for (final suffix in <String>['', '-wal', '-shm']) {
        final probe = File('${file.path}$suffix');
        if (probe.existsSync()) probe.deleteSync();
      }
    }
  });
}
