import 'dart:io';

// `hide isNull, isNotNull`: drift exports SQL expression builders of both
// names, and this file asserts with the matchers.
import 'package:drift/drift.dart' hide isNotNull, isNull;
import 'package:factorino/core/security/database_encryption_key.dart';
import 'package:factorino/data/database/app_database.dart';
import 'package:factorino/data/database/database_bootstrap.dart';
import 'package:factorino/data/database/encrypted_database.dart';
import 'package:factorino/data/models/invoice_status.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

// The old schemas, as generated by `drift_dev schema generate` for the unit
// migration tests. Imported across directories rather than duplicated: a
// hand-written copy of an old schema is a copy that can drift from the dump the
// real migration is diffed against, and then this proof would be checking a
// version that never existed.
import '../test/data/database/generated/schema_v1.dart' as v1;
import '../test/data/database/generated/schema_v3.dart' as v3;

/// The v3 -> v4 migration (D-055), on the real target.
///
/// The unit suite proves the same properties on the Dart VM. This runs on the
/// device for the reason the D-020, D-048 and D-052 proofs do: the open
/// question is whether the **native** SQLite found through Flutter's own
/// packaging path behaves the same way. `ALTER TABLE ... ADD COLUMN` on a table
/// that already holds rows, and a bulk `UPDATE` across two tables inside the
/// migration, are both things the native library decides.
///
/// **What this one adds to the earlier proofs: the backfill runs here.** It is
/// arithmetic in Dart, so the sums are not in question — what is, is that the
/// values it computes are written and read back **on the device**, over an
/// encrypted file, on columns that were added moments earlier in the same open.
/// A backfill whose UPDATEs were silently lost would leave every pre-v4 invoice
/// saying «ثبت‌نشده» forever, and no test on the VM would notice.
///
/// **Two ladders, because they are different code paths.** A device updating
/// from the last release arrives at v3 and gets all three columns new. A device
/// that has never been updated arrives at v1, and its first step rebuilds
/// `invoices` from the table as it is declared today — so the v4 step finds
/// `gross_total_rial` already present and both `invoice_items` columns absent.
/// That asymmetry is invisible in the source and is where the migration would
/// fail for exactly the users furthest behind.
///
/// Uses probe filenames, so running it never touches the real application
/// database.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  final int now = DateTime.utc(2026, 8, 24, 12).millisecondsSinceEpoch;

  Future<File> freshProbe(String name) async {
    final File file = await defaultDatabaseFile(name: name);
    for (final String suffix in <String>['', '-wal', '-shm']) {
      final File stale = File('${file.path}$suffix');
      if (stale.existsSync()) stale.deleteSync();
    }
    return file;
  }

  Future<int> pragmaInt(GeneratedDatabase db, String pragma) async {
    final QueryRow row = await db.customSelect('pragma $pragma').getSingle();
    return row.data.values.first as int;
  }

  Future<int> count(GeneratedDatabase db, String table) async {
    final QueryRow row = await db
        .customSelect('select count(*) as c from $table')
        .getSingle();
    return row.read<int>('c');
  }

  /// Everything both ladders assert about the migrated file.
  ///
  /// The fixtures are two invoices: one whose stored figures the engine can
  /// reproduce exactly, and one a single Rial away from its own inputs. The
  /// first must come back with all three figures; the second must come back
  /// with none — on the device, not only on the VM.
  Future<void> expectMigrated(
    AppDatabase migrated,
    File file, {
    required String label,
    required int versionBefore,
    required int items,
    required int payments,
  }) async {
    final int version = await pragmaInt(migrated, 'user_version');
    final int fk = await pragmaInt(migrated, 'foreign_keys');

    // soft-delete-exempt: a migration assertion over named rows.
    final InvoiceRow good = await (migrated.select(
      migrated.invoices,
    )..where((r) => r.id.equals('i-good'))).getSingle();
    // soft-delete-exempt: a migration assertion over named rows.
    final InvoiceRow bad = await (migrated.select(
      migrated.invoices,
    )..where((r) => r.id.equals('i-bad'))).getSingle();
    // soft-delete-exempt: a migration assertion over every line of one invoice.
    final List<InvoiceItemRow> goodLines =
        await (migrated.select(migrated.invoiceItems)
              ..where((r) => r.invoiceId.equals('i-good'))
              ..orderBy(<OrderClauseGenerator<$InvoiceItemsTable>>[
                (r) => OrderingTerm.asc(r.position),
              ]))
            .get();

    debugPrint(
      '=== D-055 MIGRATION PROOF ($label) on '
      '${Platform.operatingSystem} ===',
    );
    debugPrint('database file : ${file.path}');
    debugPrint('user_version  : $versionBefore -> $version');
    debugPrint('foreign_keys  : $fk');
    debugPrint('invoices      : ${await count(migrated, "invoices")}');
    debugPrint('invoice_items : ${await count(migrated, "invoice_items")}');
    debugPrint('payments      : ${await count(migrated, "payments")}');
    debugPrint('gross (good)  : ${good.grossTotalRial ?? "<null>"}');
    debugPrint('gross (bad)   : ${bad.grossTotalRial ?? "<null>"}');
    debugPrint(
      'line grosses  : '
      '${goodLines.map((InvoiceItemRow r) => r.lineGrossRial).toList()}',
    );
    debugPrint(
      'allocations   : '
      '${goodLines.map((InvoiceItemRow r) => r.allocatedInvoiceDiscountRial).toList()}',
    );
    debugPrint('file state    : ${inspectDatabaseFile(file).name}');

    // **`migrated.schemaVersion`, not a literal**, as
    // `invoice_number_migration_proof_test.dart` already had it. This one read
    // the version it was written for and kept reading it through every later
    // step, because an on-device proof is not in `flutter test` and nobody
    // re-ran it — so the assertion that says "the ladder finished" was pinned
    // to a version the application had long left behind.
    expect(version, migrated.schemaVersion);
    expect(fk, 1, reason: 'the migration must leave foreign keys on');

    // The children. `ADD COLUMN` drops nothing and neither does an `UPDATE` —
    // but the v1 ladder runs a table rebuild first, and this is the count that
    // would read zero if the device's SQLite handled the foreign-key pragma
    // differently from the VM's.
    expect(await count(migrated, 'invoice_items'), items);
    expect(await count(migrated, 'payments'), payments);

    // **The backfill, on the device.** 1,000,000 x 2.0 and 1,500,000 x 1.5,
    // the second discounted by 250,000: gross 2,000,000 + 2,250,000, and an
    // invoice discount of 100 Rial split 50/50 across two equal nets.
    expect(good.grossTotalRial, 4250000);
    expect(goodLines.map((InvoiceItemRow r) => r.lineGrossRial), <int>[
      2000000,
      2250000,
    ]);
    expect(
      goodLines.map((InvoiceItemRow r) => r.allocatedInvoiceDiscountRial),
      <int>[50, 50],
    );

    // Each line reconciles from what is stored on it, which is the property a
    // printed line needs and the reason these columns exist.
    for (final InvoiceItemRow line in goodLines) {
      expect(
        line.lineGrossRial! -
            line.discountRial -
            line.allocatedInvoiceDiscountRial!,
        line.lineNetRial,
      );
    }

    // And the summary equation, over stored figures only.
    expect(
      good.grossTotalRial! -
          good.totalDiscountRial +
          good.totalTaxRial +
          good.roundingAdjustmentRial,
      good.grandTotalRial,
    );

    // **The refusal, on the device.** One Rial out, so nothing is written —
    // not a zero, which is a number a document prints (D-055).
    expect(bad.grossTotalRial, isNull);
    expect(
      bad.grandTotalRial,
      1000000,
      reason: 'refusing to backfill must not disturb the stored totals',
    );

    // Still encrypted afterwards.
    expect(inspectDatabaseFile(file), DatabaseFileState.encrypted);

    // And the columns are writable, not merely present: every invoice saved
    // from now on writes all three, and that has to land on this device.
    await (migrated.update(migrated.invoices)
          ..where((r) => r.id.equals('i-bad')))
        .write(const InvoicesCompanion(grossTotalRial: Value<int?>(1000000)));
    // soft-delete-exempt: a migration assertion over a named row.
    final InvoiceRow written = await (migrated.select(
      migrated.invoices,
    )..where((r) => r.id.equals('i-bad'))).getSingle();
    expect(written.grossTotalRial, 1000000);
  }

  testWidgets('a v3 database upgrades to v4 and is backfilled', (_) async {
    final File file = await freshProbe('figures_probe_v3.db');
    final DatabaseEncryptionKey key =
        await const SecureStorageDatabaseKeyStore().obtain();

    final v3.DatabaseAtV3 old = v3.DatabaseAtV3(
      openEncryptedDatabase(file: file, key: key),
    );
    await old.batch((Batch batch) {
      batch.insert(
        old.settings,
        v3.SettingsCompanion.insert(id: 's', createdAt: now, updatedAt: now),
      );
      batch.insert(
        old.customers,
        v3.CustomersCompanion.insert(
          id: 'c1',
          createdAt: now,
          updatedAt: now,
          fullName: 'مشتری نمونه',
        ),
      );
      batch.insertAll(old.invoices, _goodAndBadInvoices(now));
      batch.insertAll(old.invoiceItems, _goodAndBadLines(now));
      batch.insert(
        old.payments,
        v3.PaymentsCompanion.insert(
          id: 'p1',
          createdAt: now,
          updatedAt: now,
          invoiceId: 'i-good',
          amountRial: 1000000,
          paidAt: now,
          method: 0,
        ),
      );
    });

    final int versionBefore = await pragmaInt(old, 'user_version');
    expect(versionBefore, 3, reason: 'the probe must start life as a v3 file');
    await old.close();

    final AppDatabase migrated = await openAppDatabase(file: file);
    try {
      await expectMigrated(
        migrated,
        file,
        label: 'v3 -> v4',
        versionBefore: versionBefore,
        items: 3,
        payments: 1,
      );
    } finally {
      await migrated.close();
      for (final String suffix in <String>['', '-wal', '-shm']) {
        final File probe = File('${file.path}$suffix');
        if (probe.existsSync()) probe.deleteSync();
      }
    }
  });

  testWidgets('a v1 database reaches v4 through all three steps', (_) async {
    // The device that has not been updated since the first release. Its first
    // step rebuilds `invoices` at the current declaration, so the third finds
    // `gross_total_rial` already present while both `invoice_items` columns are
    // still absent — the path where a plain `addColumn` fails with `duplicate
    // column name`, on open, leaving the database unopenable for exactly the
    // users furthest behind.
    final File file = await freshProbe('figures_probe_v1.db');
    final DatabaseEncryptionKey key =
        await const SecureStorageDatabaseKeyStore().obtain();

    final v1.DatabaseAtV1 old = v1.DatabaseAtV1(
      openEncryptedDatabase(file: file, key: key),
    );
    await old.batch((Batch batch) {
      batch.insert(
        old.settings,
        v1.SettingsCompanion.insert(id: 's', createdAt: now, updatedAt: now),
      );
      batch.insert(
        old.customers,
        v1.CustomersCompanion.insert(
          id: 'c1',
          createdAt: now,
          updatedAt: now,
          fullName: 'مشتری نمونه',
        ),
      );

      // v1 required a number on every invoice (D-048 is what made it
      // nullable), so both fixtures carry one here.
      batch.insertAll(old.invoices, <v1.InvoicesCompanion>[
        v1.InvoicesCompanion.insert(
          id: 'i-good',
          createdAt: now,
          updatedAt: now,
          number: 'INV-1405-0001',
          numberYear: 1405,
          numberSequence: 1,
          customerId: 'c1',
          issueDate: now,
          status: InvoiceStatus.unpaid.index,
          discountRial: const Value<int>(100),
          subtotalRial: const Value<int>(4000000),
          totalDiscountRial: const Value<int>(250100),
          totalTaxRial: const Value<int>(0),
          grandTotalRial: const Value<int>(3999900),
        ),
        v1.InvoicesCompanion.insert(
          id: 'i-bad',
          createdAt: now,
          updatedAt: now,
          number: 'INV-1405-0002',
          numberYear: 1405,
          numberSequence: 2,
          customerId: 'c1',
          issueDate: now,
          status: InvoiceStatus.unpaid.index,
          subtotalRial: const Value<int>(1000000),
          grandTotalRial: const Value<int>(1000000),
        ),
      ]);
      batch.insertAll(old.invoiceItems, <v1.InvoiceItemsCompanion>[
        v1.InvoiceItemsCompanion.insert(
          id: 'good-0',
          createdAt: now,
          updatedAt: now,
          invoiceId: 'i-good',
          position: const Value<int>(0),
          titleSnapshot: 'خدمات',
          unitSnapshot: 'عدد',
          unitPriceRial: 1000000,
          quantityMilli: 2000,
          resolvedTaxRateBp: 0,
          lineNetRial: const Value<int>(1999950),
          lineTotalRial: const Value<int>(1999950),
        ),
        v1.InvoiceItemsCompanion.insert(
          id: 'good-1',
          createdAt: now,
          updatedAt: now,
          invoiceId: 'i-good',
          position: const Value<int>(1),
          titleSnapshot: 'مشاوره',
          unitSnapshot: 'ساعت',
          unitPriceRial: 1500000,
          quantityMilli: 1500,
          resolvedTaxRateBp: 0,
          discountRial: const Value<int>(250000),
          lineNetRial: const Value<int>(1999950),
          lineTotalRial: const Value<int>(1999950),
        ),
        v1.InvoiceItemsCompanion.insert(
          id: 'bad-0',
          createdAt: now,
          updatedAt: now,
          invoiceId: 'i-bad',
          titleSnapshot: 'قلم مبهم',
          unitSnapshot: 'عدد',
          unitPriceRial: 1000000,
          quantityMilli: 1000,
          resolvedTaxRateBp: 0,
          lineNetRial: const Value<int>(999999),
          lineTotalRial: const Value<int>(999999),
        ),
      ]);
      batch.insert(
        old.payments,
        v1.PaymentsCompanion.insert(
          id: 'p1',
          createdAt: now,
          updatedAt: now,
          invoiceId: 'i-good',
          amountRial: 1000000,
          paidAt: now,
          method: 0,
        ),
      );
    });

    final int versionBefore = await pragmaInt(old, 'user_version');
    expect(versionBefore, 1, reason: 'the probe must start life as a v1 file');
    await old.close();

    final AppDatabase migrated = await openAppDatabase(file: file);
    try {
      await expectMigrated(
        migrated,
        file,
        label: 'v1 -> v4',
        versionBefore: versionBefore,
        items: 3,
        payments: 1,
      );
    } finally {
      await migrated.close();
      for (final String suffix in <String>['', '-wal', '-shm']) {
        final File probe = File('${file.path}$suffix');
        if (probe.existsSync()) probe.deleteSync();
      }
    }
  });
}

/// The two invoices both ladders seed: one the engine can account for, one it
/// cannot.
///
/// The reconcilable one carries an invoice-level discount of 100 Rial across
/// two equal nets, so the allocation is 50/50 — a figure that exists nowhere in
/// the fixture and has to be worked out.
List<v3.InvoicesCompanion> _goodAndBadInvoices(int now) {
  return <v3.InvoicesCompanion>[
    v3.InvoicesCompanion.insert(
      id: 'i-good',
      createdAt: now,
      updatedAt: now,
      number: const Value<String>('INV-1405-0001'),
      numberYear: const Value<int>(1405),
      numberSequence: const Value<int>(1),
      customerId: 'c1',
      issueDate: now,
      status: InvoiceStatus.unpaid.index,
      discountRial: const Value<int>(100),
      subtotalRial: const Value<int>(4000000),
      totalDiscountRial: const Value<int>(250100),
      grandTotalRial: const Value<int>(3999900),
    ),
    v3.InvoicesCompanion.insert(
      id: 'i-bad',
      createdAt: now,
      updatedAt: now,
      number: const Value<String>('INV-1405-0002'),
      numberYear: const Value<int>(1405),
      numberSequence: const Value<int>(2),
      customerId: 'c1',
      issueDate: now,
      status: InvoiceStatus.unpaid.index,
      subtotalRial: const Value<int>(1000000),
      grandTotalRial: const Value<int>(1000000),
    ),
  ];
}

List<v3.InvoiceItemsCompanion> _goodAndBadLines(int now) {
  return <v3.InvoiceItemsCompanion>[
    v3.InvoiceItemsCompanion.insert(
      id: 'good-0',
      createdAt: now,
      updatedAt: now,
      invoiceId: 'i-good',
      position: const Value<int>(0),
      titleSnapshot: 'خدمات',
      unitSnapshot: 'عدد',
      unitPriceRial: 1000000,
      quantityMilli: 2000,
      resolvedTaxRateBp: 0,
      lineNetRial: const Value<int>(1999950),
      lineTotalRial: const Value<int>(1999950),
    ),
    v3.InvoiceItemsCompanion.insert(
      id: 'good-1',
      createdAt: now,
      updatedAt: now,
      invoiceId: 'i-good',
      position: const Value<int>(1),
      titleSnapshot: 'مشاوره',
      unitSnapshot: 'ساعت',
      unitPriceRial: 1500000,
      quantityMilli: 1500,
      resolvedTaxRateBp: 0,
      discountRial: const Value<int>(250000),
      lineNetRial: const Value<int>(1999950),
      lineTotalRial: const Value<int>(1999950),
    ),
    v3.InvoiceItemsCompanion.insert(
      id: 'bad-0',
      createdAt: now,
      updatedAt: now,
      invoiceId: 'i-bad',
      titleSnapshot: 'قلم مبهم',
      unitSnapshot: 'عدد',
      unitPriceRial: 1000000,
      quantityMilli: 1000,
      resolvedTaxRateBp: 0,
      lineNetRial: const Value<int>(999999),
      lineTotalRial: const Value<int>(999999),
    ),
  ];
}
