import 'dart:io';

// `hide isNull, isNotNull`: drift exports SQL expression builders of both
// names, and this file asserts with the matchers.
import 'package:drift/drift.dart' hide isNotNull, isNull;
import 'package:factorino/core/security/database_encryption_key.dart';
import 'package:factorino/data/database/app_database.dart';
import 'package:factorino/data/database/database_bootstrap.dart';
import 'package:factorino/data/database/encrypted_database.dart';
import 'package:factorino/data/models/app_settings.dart';
import 'package:factorino/data/models/seller_identity.dart';
import 'package:factorino/data/repositories/drift/drift_settings_repository.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

// The old schemas, as generated by `drift_dev schema generate` for the unit
// migration tests. Imported across directories rather than duplicated: a
// hand-written copy of an old schema is a copy that can drift from the dump the
// real migration is diffed against, and then this proof would be checking a
// version that never existed.
import '../test/data/database/generated/schema_v1.dart' as v1;
import '../test/data/database/generated/schema_v4.dart' as v4;

/// The v4 -> v5 migration (D-077), on the real target.
///
/// The unit suite proves the same properties on the Dart VM. This runs on the
/// device for the reason the D-020, D-048, D-052 and D-055 proofs do: the open
/// question is whether the **native** SQLite found through Flutter's own
/// packaging path behaves the same way. `ALTER TABLE ... ADD COLUMN` on a table
/// that already holds a row, under a `CHECK` constraint, is something the
/// native library decides.
///
/// **What this proof is mostly about is an absence**, which makes it unusual
/// among the four. The three earlier steps each had something to write; this
/// one adds four columns and writes nothing into any of them, permanently and
/// on purpose — the database has never been told anything about the user's
/// business, so there is nothing to compute and nothing to copy. The failure it
/// is arranged against is a **plausible-looking value**: a default, or a
/// leftover, that would put a business name nobody typed onto the one page the
/// customer keeps, where it would look exactly like a real one.
///
/// **Two ladders, because they are different code paths.** A device updating
/// from the last release arrives at v4. A device that has never been updated
/// arrives at v1 and runs a table rebuild and a backfill before it gets here.
/// `settings` is rebuilt by no step, so all four columns are absent on both
/// paths today — but the ladder is what would break first if that ever stopped
/// being true, and it breaks on open, for the users furthest behind, and for
/// nobody else.
///
/// Uses probe filenames, so running it never touches the real application
/// database.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  final int now = DateTime.utc(2026, 9, 2, 12).millisecondsSinceEpoch;

  Future<File> freshProbe(String name) async {
    final File file = await defaultDatabaseFile(name: name);
    for (final String suffix in <String>['', '-wal', '-shm']) {
      final File stale = File('${file.path}$suffix');
      if (stale.existsSync()) stale.deleteSync();
    }
    return file;
  }

  Future<int> pragmaInt(GeneratedDatabase db, String pragma) async {
    final QueryRow row = await db.customSelect('pragma $pragma').getSingle();
    return row.data.values.first as int;
  }

  Future<int> count(GeneratedDatabase db, String table) async {
    final QueryRow row = await db
        .customSelect('select count(*) as c from $table')
        .getSingle();
    return row.read<int>('c');
  }

  /// Everything both ladders assert about the migrated file.
  Future<void> expectMigrated(
    AppDatabase migrated,
    File file, {
    required String label,
    required int versionBefore,
  }) async {
    final int version = await pragmaInt(migrated, 'user_version');
    final int fk = await pragmaInt(migrated, 'foreign_keys');

    // soft-delete-exempt: the single configuration row, read by identity.
    final SettingsRow row = await migrated
        .select(migrated.settings)
        .getSingle();

    debugPrint(
      '=== D-077 MIGRATION PROOF ($label) on ${Platform.operatingSystem} ===',
    );
    debugPrint('database file : ${file.path}');
    debugPrint('user_version  : $versionBefore -> $version');
    debugPrint('foreign_keys  : $fk');
    debugPrint('settings rows : ${await count(migrated, "settings")}');
    debugPrint('customers     : ${await count(migrated, "customers")}');
    debugPrint('invoices      : ${await count(migrated, "invoices")}');
    // The three columns, by presence rather than by content: a business name
    // is a user identifier and §7 keeps those out of any log, in any build.
    // There were four until v7 dropped کد اقتصادی (D-106).
    debugPrint(
      'seller_name   : ${row.sellerName == null ? "<null>" : "<set>"}',
    );
    debugPrint(
      'seller_addr   : ${row.sellerAddress == null ? "<null>" : "<set>"}',
    );
    debugPrint(
      'seller_phone  : ${row.sellerPhone == null ? "<null>" : "<set>"}',
    );
    debugPrint('tax rate bp   : ${row.defaultTaxRateBp}');
    debugPrint('prefix        : ${row.invoiceNumberPrefix}');
    debugPrint('payment term  : ${row.paymentTermDays}');
    debugPrint('file state    : ${inspectDatabaseFile(file).name}');

    // **`migrated.schemaVersion`, not a literal.** This read `5` and went on
    // reading it through the v6 theme column and the v7 economic-id removal,
    // because an on-device proof is not in `flutter test` and nobody re-ran it
    // — so the one assertion that says "the ladder finished" was pinned to a
    // version the application had left behind twice. A literal here rots
    // silently every time the schema moves.
    expect(version, migrated.schemaVersion);
    expect(fk, 1, reason: 'the migration must leave foreign keys on');

    // **The single row is still single.** `settings` carries
    // `CHECK (singleton = 1)`; a step that duplicated or dropped it would leave
    // `getSingle` throwing on every read in the application, on this device,
    // at startup.
    expect(await count(migrated, 'settings'), 1);
    expect(await count(migrated, 'customers'), 1);
    expect(await count(migrated, 'invoices'), 1);

    // **Three nulls, on the device.** Not "the columns exist" — a default
    // would satisfy that and would print an invented seller on a
    // customer-facing page.
    expect(row.sellerName, isNull);
    expect(row.sellerAddress, isNull);
    expect(row.sellerPhone, isNull);

    // And the settings the user already had, untouched. The fixture is not the
    // seeded defaults for exactly this reason: a step that reset the row would
    // pass every assertion made against 1000 / INV / 30.
    expect(row.defaultTaxRateBp, 900);
    expect(row.invoiceNumberPrefix, 'FCT');

    // Still encrypted afterwards.
    expect(inspectDatabaseFile(file), DatabaseFileState.encrypted);

    // **The columns are writable, not merely present.** A column added by a
    // migration that then refuses writes is a defect the user meets the first
    // time they fill the settings form in — days after the update, with no way
    // to connect the two. Through the real repository, on the migrated file.
    final DriftSettingsRepository repository = DriftSettingsRepository(
      migrated,
    );
    await repository.write(
      (await repository.read()).copyWith(
        seller: const SellerIdentity(
          name: 'کارگاه صنعتی نمونه پارس',
          address: 'تهران، خیابان ولی‌عصر، پلاک ۱۲۳',
          phone: '02188776655',
        ),
      ),
    );

    final AppSettings after = await repository.read();
    expect(after.seller.name, 'کارگاه صنعتی نمونه پارس');
    expect(after.seller.address, 'تهران، خیابان ولی‌عصر، پلاک ۱۲۳');
    expect(after.seller.phone, '02188776655');
    expect(after.seller.isPrintable, isTrue);
    debugPrint('write-back    : OK, isPrintable=${after.seller.isPrintable}');

    // **And clearing reaches the columns as nulls**, which is the case
    // `copyWith` on four nullable strings could not express and the reason
    // `SellerIdentity` is a value object. Proved here because the failure —
    // the old name written straight back — would be invisible until the next
    // document was printed.
    await repository.write(
      (await repository.read()).copyWith(seller: SellerIdentity.none),
    );
    // soft-delete-exempt: the single configuration row, read by identity.
    final SettingsRow cleared = await migrated
        .select(migrated.settings)
        .getSingle();
    expect(cleared.sellerName, isNull);
    expect(cleared.sellerPhone, isNull);
    debugPrint('clear-back    : OK, all three null again');
  }

  testWidgets('a v4 database upgrades with an empty seller', (_) async {
    final File file = await freshProbe('seller_probe_v4.db');
    final DatabaseEncryptionKey key =
        await const SecureStorageDatabaseKeyStore().obtain();

    final v4.DatabaseAtV4 old = v4.DatabaseAtV4(
      openEncryptedDatabase(file: file, key: key),
    );
    await old.batch((Batch batch) {
      batch.insert(
        old.settings,
        v4.SettingsCompanion.insert(
          id: 's',
          createdAt: now,
          updatedAt: now,
          defaultTaxRateBp: const Value<int>(900),
          invoiceNumberPrefix: const Value<String>('FCT'),
          paymentTermDays: const Value<int>(45),
        ),
      );
      batch.insert(
        old.customers,
        v4.CustomersCompanion.insert(
          id: 'c1',
          createdAt: now,
          updatedAt: now,
          fullName: 'مشتری نمونه',
        ),
      );
      batch.insert(
        old.invoices,
        v4.InvoicesCompanion.insert(
          id: 'i1',
          createdAt: now,
          updatedAt: now,
          number: const Value<String>('FCT-1405-0001'),
          numberYear: const Value<int>(1405),
          numberSequence: const Value<int>(1),
          customerId: 'c1',
          issueDate: now,
          status: 1,
          subtotalRial: const Value<int>(1000000),
          grandTotalRial: const Value<int>(1000000),
        ),
      );
    });

    final int versionBefore = await pragmaInt(old, 'user_version');
    expect(versionBefore, 4, reason: 'the probe must start life as a v4 file');
    await old.close();

    final AppDatabase migrated = await openAppDatabase(file: file);
    try {
      await expectMigrated(
        migrated,
        file,
        label: 'v4 -> v5',
        versionBefore: versionBefore,
      );
    } finally {
      await migrated.close();
      for (final String suffix in <String>['', '-wal', '-shm']) {
        final File probe = File('${file.path}$suffix');
        if (probe.existsSync()) probe.deleteSync();
      }
    }
  });

  testWidgets('a v1 database reaches the current version', (_) async {
    // The device that has not been updated since the first release: a table
    // rebuild, every column addition, a backfill and the v7 drops, all in one
    // open on an encrypted file with foreign keys on.
    final File file = await freshProbe('seller_probe_v1.db');
    final DatabaseEncryptionKey key =
        await const SecureStorageDatabaseKeyStore().obtain();

    final v1.DatabaseAtV1 old = v1.DatabaseAtV1(
      openEncryptedDatabase(file: file, key: key),
    );
    await old.batch((Batch batch) {
      batch.insert(
        old.settings,
        v1.SettingsCompanion.insert(
          id: 's',
          createdAt: now,
          updatedAt: now,
          defaultTaxRateBp: const Value<int>(900),
          invoiceNumberPrefix: const Value<String>('FCT'),
        ),
      );
      batch.insert(
        old.customers,
        v1.CustomersCompanion.insert(
          id: 'c1',
          createdAt: now,
          updatedAt: now,
          fullName: 'مشتری نمونه',
        ),
      );
      // v1 required a number on every invoice; D-048 is what made it nullable.
      batch.insert(
        old.invoices,
        v1.InvoicesCompanion.insert(
          id: 'i1',
          createdAt: now,
          updatedAt: now,
          number: 'FCT-1405-0001',
          numberYear: 1405,
          numberSequence: 1,
          customerId: 'c1',
          issueDate: now,
          status: 1,
          subtotalRial: const Value<int>(1000000),
          grandTotalRial: const Value<int>(1000000),
        ),
      );
    });

    final int versionBefore = await pragmaInt(old, 'user_version');
    expect(versionBefore, 1, reason: 'the probe must start life as a v1 file');
    await old.close();

    final AppDatabase migrated = await openAppDatabase(file: file);
    try {
      await expectMigrated(
        migrated,
        file,
        label: 'v1 -> v5',
        versionBefore: versionBefore,
      );
    } finally {
      await migrated.close();
      for (final String suffix in <String>['', '-wal', '-shm']) {
        final File probe = File('${file.path}$suffix');
        if (probe.existsSync()) probe.deleteSync();
      }
    }
  });
}
